### ISSUE TITLE
MAYBE TODO for paper: Multimodal models 

### ISSUE THREAD

**Issue by annashcherbina** [kundajelab/DMSO#17]
Anshul -- should we aim to have this for the paper or for a later time? 

Option 1: Add RNA-seq values as channel 5 in the inputs to the DL model. 

Option 2: Add RNA-seq values as a separate input layer and combine with sequence data via a merge layer (sequence data goes through several conv layers prior to merge operation).

**Comment by akundaje** [comment]
No this wont really work given the few time points we have.
